const fs = require('fs');
const assert = require('assert');
const path = require('path');

const root = path.resolve(__dirname, '..');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const inventory = fs.readFileSync(path.join(root, 'public/js/views/InventoryManagement.js'), 'utf8');
const orders = fs.readFileSync(path.join(root, 'public/js/views/OrderList.js'), 'utf8');
const listing = fs.readFileSync(path.join(root, 'public/js/views/ListingHistory.js'), 'utf8');
const main = fs.readFileSync(path.join(root, 'public/js/main.js'), 'utf8');
const batchUpload = fs.readFileSync(path.join(root, 'public/js/views/BatchUpload.js'), 'utf8');
const stores = fs.readFileSync(path.join(root, 'public/js/views/StoreManagement.js'), 'utf8');
const shopSwitcher = fs.readFileSync(path.join(root, 'public/js/components/ShopSwitcher.js'), 'utf8');

for (const table of ['app_stock_drafts', 'app_stock_change_logs']) assert(server.includes(`CREATE TABLE IF NOT EXISTS ${table}`));
for (const route of [
  '/api/seller/stocks/drafts',
  '/api/seller/stocks/save-draft',
  '/api/seller/stocks/import',
  '/api/seller/stocks/change-logs',
  '/api/seller/products/stocks/bulk',
]) assert(server.includes(route), `missing route ${route}`);
assert(server.includes('drafts.slice(index, index + 100)'));
assert(server.includes('fetchLiveStocksByOffer'));
assert(server.includes('code: "STOCK_CONFLICT"'));
assert(server.includes("'conflict'"));
assert(inventory.includes('submitAllDrafts'));
assert(inventory.includes('saveStockDrafts'));
assert(inventory.includes('inventoryLowStockThreshold'));
assert(inventory.includes('inventoryStats'));
assert(inventory.includes('lastImportResult'), 'inventory must keep the last import result visible after toast disappears');
assert(inventory.includes('库存导入失败明细'), 'inventory import errors must be visible in-page');
assert(inventory.includes('lastSubmitResult'), 'inventory must keep the last stock submit result visible after toast disappears');
assert(inventory.includes('库存提交失败明细'), 'inventory Ozon submit errors must be visible in-page');
assert(inventory.includes('window.XLSX'));
assert(inventory.includes('exportReplenishment'));
assert(inventory.includes('submitWithConflictCheck'));
assert(inventory.includes('发现 Ozon 实时库存冲突'));
assert(inventory.includes('库存变更记录'));
assert(server.includes('当前店铺有多个仓库，请在文件中填写 warehouse_id'));
assert(server.includes('app.post("/api/seller/stocks/import", requireAuth'));
assert(server.includes('app.patch("/api/products/:offer_id/field", requireAuth'));
assert(server.includes('function enrichWarehouseReadModel'), 'warehouse APIs must expose display-safe warehouse fields');
assert(server.includes('status_display: warehouseStatusDisplay(warehouse.status)'), 'warehouse rows must include Chinese status_display');
assert(server.includes('source_display: warehouseSourceDisplay(source)'), 'warehouse rows must include Chinese source_display');
assert(server.includes('warehouses: merged.map(enrichWarehouseReadModel)'), 'stock detail must return enriched warehouse rows');
assert(server.includes('items: result.rows.map(enrichProductReadModel)'), 'inventory list must return enriched product read models');

assert(server.includes('ON CONFLICT (store_id, posting_number)'));
assert(server.includes('CREATE TABLE IF NOT EXISTS app_order_ship_events'));
assert(server.includes('app.post("/api/seller/orders/labels", requireAuth'));
assert(server.includes('inventoryAdjusted'));
assert(server.includes('ORDER_SHIP_IN_PROGRESS'));
assert(server.includes('ORDER_ALREADY_SHIPPED'));
assert(server.includes('ORDER_CANCELLED'));
assert(server.includes("status='ozon_succeeded'"));
assert(server.includes('Ozon 已接收发货，但本地库存更新失败'));
assert(server.includes('实际发货时间'));
assert(server.includes('采购成本(CNY)'));
assert(server.includes('status.toLowerCase() !== "all"'));
assert(server.includes('当前 Ozon Seller API 未提供可靠的逐节点物流轨迹'));
assert(orders.includes('batchShip'));
assert(orders.includes('lastBatchResult'), 'orders must keep the last batch action result visible after toast disappears');
assert(orders.includes('订单操作失败明细'), 'orders must show per-order batch failure details in-page');
assert(orders.includes('exportOrders'));
assert(orders.includes('printLabels'));
assert(orders.includes('saveNote'));
assert(orders.includes("row.status !== 'cancelled'"));
assert(orders.includes('source_url_1688'), 'orders must expose the product procurement link');
assert(orders.includes("split(',')"), 'orders must normalize duplicated store ids');
assert(orders.includes("{ label: '争议中', value: 'arbitration' }"));
assert(orders.includes("if (!['awaiting_packaging', 'awaiting_deliver'].includes(row.status))"));
assert(orders.includes('statusText(row.status)'));
assert(orders.includes('暂无匹配订单。可调整状态或日期范围后刷新；这里只显示当前店铺订单。'), 'orders must explain empty filters and current-store scope');
assert(orders.includes('确认发货至 Ozon'), 'orders must avoid exposing raw API endpoint text in the ship button');

assert(listing.includes("store_id: getStoreId() || undefined"));
assert(listing.includes("axios.get('/api/seller/listing-history', { params })"));
assert(listing.includes('syncTask'));
assert(listing.includes('pagination.currentPage'));
assert(listing.includes('retryTask'));
assert(listing.includes('exportHistory'));
assert(listing.includes('message_zh'));
assert(listing.includes('firstErrorText'), 'listing history must prefer backend first-error summaries in the visible table');
assert(listing.includes('error_summary'), 'listing history must consume backend error_summary when present');
assert(listing.includes('错误摘要'), 'listing detail must show a readable error summary before raw errors');
assert(server.includes('req.body?.taskId || req.body?.task_id'));
assert(server.includes('translateOzonListingError'));
assert(server.includes('/api/seller/listing-history/:id/retry'));
assert(server.includes('/api/seller/listing-history/export'));
assert(server.includes('function listingErrorSummary'), 'listing history must expose first-error and summary fields');
assert(server.includes('error_summary: readable.slice(0, 3).join("；")'), 'listing history must include human-readable error_summary');
assert(server.includes('first_error_message_zh'), 'listing history must include translated first error');
assert(server.includes("lh.task_id ILIKE"));
assert(server.includes("interval '1 day'"));
assert(!main.includes('<span>单品找货</span>'), 'single sourcing must not be a normal sidebar entry while frozen');
assert(main.includes("routeName === 'single-sourcing-frozen'"), 'single sourcing route must render a frozen notice');
assert(listing.includes("'ozon_processing'"), 'listing history must understand ozon_processing status');
assert(listing.includes('同步状态'), 'listing history must provide a clear sync action');
assert(listing.includes('部分商品需处理后重试'), 'listing history must explain partial success');
assert(listing.includes('label="partial_success"'), 'listing history must expose a partial-success filter');
assert(listing.includes('上架记录列表'), 'listing history should use user-facing listing history copy');
assert(listing.includes('暂无匹配的上架记录。可调整筛选条件；新记录会在批量上架提交后出现。'), 'listing history must have a non-misleading empty state');
assert(inventory.includes('暂无库存数据。请先选择店铺并点击同步 Ozon 全量；如已同步，可调整搜索条件。'), 'inventory must explain empty data and next step');
assert(batchUpload.includes('这不是创建完成'), 'batch upload completion copy must distinguish submitted from completed');
assert(stores.includes('PLUGIN_MANIFEST_VERSION'), 'store management must expose manifest version');
assert(stores.includes('PLUGIN_ZIP_VERSION'), 'store management must expose zip version');
assert(stores.includes('需要刷新插件'), 'store management must show plugin refresh guidance');
assert(stores.includes('小白检查顺序'), 'store management must show non-technical plugin install checks');
assert(stores.includes('批量上架开启水印增强时会使用此文字'), 'store management must explain how watermark text is used');
assert(stores.includes('refreshPluginStatus'), 'store management must allow refreshing plugin status');
assert(stores.includes('displayClientId'), 'store management must use a client id display helper');
assert(stores.includes('不会删除 Ozon 后台店铺'), 'store deletion must explain it only removes ERP authorization');
assert(stores.includes('暂无店铺授权。新增授权后才能同步商品、库存、订单和采集任务。'), 'store management must explain empty state');
assert(stores.includes('row.client_id_masked'), 'store management must prefer backend masked client id');
assert(stores.includes('row.client_id_last4'), 'store management must support backend client id last4 fallback');
assert(stores.includes('maskClientId(row.client_id)'), 'store management must keep legacy local masking fallback');
assert(shopSwitcher.includes('displayClientId'), 'shop switcher must use a client id display helper');
assert(shopSwitcher.includes('shop.client_id_masked'), 'shop switcher must prefer backend masked client id');
assert(shopSwitcher.includes('shop.client_id_last4'), 'shop switcher must support backend client id last4 fallback');
assert(shopSwitcher.includes('maskClientId(shop.client_id)'), 'shop switcher must keep legacy local masking fallback');

console.log('Inventory, orders, and listing history structural checks passed.');
