const fs = require('fs');
const assert = require('assert');

const server = fs.readFileSync('server.js', 'utf8');
const view = fs.readFileSync('public/js/views/AnalyticsCenter.js', 'utf8');
const main = fs.readFileSync('public/js/main.js', 'utf8');
const html = fs.readFileSync('public/index.html', 'utf8');

assert.match(server, /WHERE active = TRUE AND user_id = \$1/);
assert.match(server, /offset < 5000/);
assert.match(server, /profit_complete: storeData\.every/);
assert.match(server, /totalReturns = storeData\.reduce\(\(s, x\) => s \+ \(x\._returns7d \|\| 0\), 0\)/);
assert.match(server, /async function validateOzonCredentials/);
assert.match(server, /active = FALSE/);
assert.match(server, /api_key = \$4, active = TRUE/);
assert.match(view, /\/api\/seller\/dashboard/);
assert.match(view, /\/api\/seller\/analytics\/categories/);
assert.match(view, /\/api\/seller\/analytics\/bestsellers/);
assert.match(view, /profitRows/);
assert.match(view, /purchase_cost_cny/);
assert.match(server, /profit_is_estimated/);
assert.match(server, /commissionCny \* qty/);
assert.match(view, /不再显示猜测利润/);
assert.match(view, /\/api\/finance\/product-cost/);
assert.match(view, /\/api\/finance\/exchange-rate/);
assert.match(view, /成本变更记录/);
assert.match(server, /CREATE TABLE IF NOT EXISTS app_product_cost_audit/);
assert.match(server, /CREATE TABLE IF NOT EXISTS app_exchange_rates/);
assert.match(server, /尚无可核算利润/);
assert.match(main, /analytics-center-view/);
assert.match(html, /AnalyticsCenter\.js/);
console.log('Analytics center structural checks passed.');
