const fs = require('fs');
const assert = require('assert');
const path = require('path');

const root = path.resolve(__dirname, '..');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const inventory = fs.readFileSync(path.join(root, 'public/js/views/InventoryManagement.js'), 'utf8');
const orders = fs.readFileSync(path.join(root, 'public/js/views/OrderList.js'), 'utf8');
const listing = fs.readFileSync(path.join(root, 'public/js/views/ListingHistory.js'), 'utf8');
const main = fs.readFileSync(path.join(root, 'public/js/main.js'), 'utf8');
const sourcing = fs.readFileSync(path.join(root, 'public/js/views/SourcingModule.js'), 'utf8');
const batchUpload = fs.readFileSync(path.join(root, 'public/js/views/BatchUpload.js'), 'utf8');
const stores = fs.readFileSync(path.join(root, 'public/js/views/StoreManagement.js'), 'utf8');
const shopSwitcher = fs.readFileSync(path.join(root, 'public/js/components/ShopSwitcher.js'), 'utf8');

for (const table of ['app_stock_drafts', 'app_stock_change_logs']) assert(server.includes(`CREATE TABLE IF NOT EXISTS ${table}`));
for (const route of [
  '/api/seller/stocks/drafts',
  '/api/seller/stocks/save-draft',
  '/api/seller/stocks/import',
  '/api/seller/stocks/change-logs',
  '/api/seller/products/stocks/bulk',
]) assert(server.includes(route), `missing route ${route}`);
assert(server.includes('drafts.slice(index, index + 100)'));
assert(server.includes('fetchLiveStocksByOffer'));
assert(server.includes('code: "STOCK_CONFLICT"'));
assert(server.includes("'conflict'"));
assert(inventory.includes('submitAllDrafts'));
assert(inventory.includes('saveStockDrafts'));
assert(inventory.includes('selectedInventory'), 'inventory must support selecting multiple products for bulk stock updates');
assert(inventory.includes('bulkStockDialog'), 'inventory must expose a bulk stock edit dialog');
assert(inventory.includes('批量设置库存'), 'inventory must provide a visible bulk stock action');
assert(inventory.includes('saveBulkStockDrafts'), 'inventory bulk stock edit must reuse stock draft saving');
assert(inventory.includes("ids: savedIds"), 'inventory bulk stock submit must submit only the newly saved drafts');
assert(inventory.includes('inventoryLowStockThreshold'));
assert(inventory.includes('inventoryStats'));
assert(inventory.includes('lastImportResult'), 'inventory must keep the last import result visible after toast disappears');
assert(inventory.includes('库存导入失败明细'), 'inventory import errors must be visible in-page');
assert(inventory.includes('lastSubmitResult'), 'inventory must keep the last stock submit result visible after toast disappears');
assert(inventory.includes('库存提交失败明细'), 'inventory Ozon submit errors must be visible in-page');
assert(inventory.includes('window.XLSX'));
assert(inventory.includes('exportReplenishment'));
assert(inventory.includes('submitWithConflictCheck'));
assert(inventory.includes('发现 Ozon 实时库存冲突'));
assert(inventory.includes('库存变更记录'));
assert(inventory.includes('class="inventory-container" style="background:#f8fafc'), 'inventory must use the unified ERP workbench shell');
assert(inventory.includes('element-loading-text="正在读取库存"'), 'inventory table must use the unified loading state');
assert(inventory.includes('<MoreFilled />'), 'inventory row actions must use a compact overflow trigger');
assert(inventory.includes('批量改库存 ({{ selectedInventory.length }})'), 'inventory bulk stock action must be visible in the workbench toolbar');
assert(server.includes('当前店铺有多个仓库，请在文件中填写 warehouse_id'));
assert(server.includes('app.post("/api/seller/stocks/import", requireAuth'));
assert(server.includes('app.patch("/api/products/:offer_id/field", requireAuth'));
assert(server.includes('function enrichWarehouseReadModel'), 'warehouse APIs must expose display-safe warehouse fields');
assert(server.includes('status_display: warehouseStatusDisplay(warehouse.status)'), 'warehouse rows must include Chinese status_display');
assert(server.includes('source_display: warehouseSourceDisplay(source)'), 'warehouse rows must include Chinese source_display');
assert(server.includes('warehouses: merged.map(enrichWarehouseReadModel)'), 'stock detail must return enriched warehouse rows');
assert(server.includes('items: result.rows.map(enrichProductReadModel)'), 'inventory list must return enriched product read models');
assert(server.includes('livePage = await fetchOzonProductListPage(storeId, userId, "ALL", limit, offset)'), 'inventory list must use the current Ozon product page instead of stale local cache');
assert(server.includes("LOWER(COALESCE(status, '')) NOT IN ('in_active', 'archived', 'deleted')"), 'inventory list must exclude archived products');
assert(server.includes("visibility_details->>'archived'"), 'inventory list must exclude Ozon archived products');

assert(server.includes('ON CONFLICT (store_id, posting_number)'));
assert(server.includes('CREATE TABLE IF NOT EXISTS app_order_ship_events'));
assert(server.includes('CREATE TABLE IF NOT EXISTS app_order_cancel_events'), 'orders must record cancel intent without calling Ozon in test env');
assert(server.includes('CREATE TABLE IF NOT EXISTS app_order_cache'), 'orders must keep a MY ERP style local posting cache');
assert(server.includes('syncCacheWindow(defaultCacheHistoryDays)'), 'orders must backfill the default cache instead of counting only the current live page window');
assert(server.includes('source: "cache"'), 'default order list must read from the local posting cache');
assert(server.includes('inventoryAdjusted'));
assert(server.includes('ORDER_SHIP_IN_PROGRESS'));
assert(server.includes('ORDER_ALREADY_SHIPPED'));
assert(server.includes('ORDER_CANCELLED'));
assert(server.includes("status='ozon_succeeded'"));
assert(server.includes('Ozon 已接收发货，但本地库存更新失败'));
assert(server.includes('实际发货时间'));
assert(server.includes('采购成本(CNY)'));
assert(server.includes('status.toLowerCase() !== "all"'));
assert(server.includes('当前 Ozon Seller API 未提供可靠的逐节点物流轨迹'));
assert(orders.includes('batchShip'));
assert(orders.includes('lastBatchResult'), 'orders must keep the last batch action result visible after toast disappears');
assert(orders.includes('订单操作失败明细'), 'orders must show per-order batch failure details in-page');
assert(orders.includes('exportOrders'));
assert(!orders.includes('printLabels'));
assert(!orders.includes('面单'));
assert(orders.includes('saveNote'));
assert(orders.includes('orderNote'), 'orders must expose saved notes in the visible row');
assert(orders.includes('label="备注"'), 'orders must expose notes as a dedicated table column');
assert(orders.includes("row.status !== 'cancelled'"));
assert(!orders.includes('batchArchive'), 'order management must not expose archive actions');
assert(!orders.includes("{ label: '已归档', value: 'archived' }"), 'order management must not add an archived status tab');
assert(orders.includes('source_url_1688'), 'orders must expose the product procurement link');
assert(orders.includes("split(',')"), 'orders must normalize duplicated store ids');
assert(orders.includes("{ label: '有争议的', value: 'arbitration' }"));
assert(orders.includes("{ label: '已超时', value: 'overdue' }"));
assert(orders.includes("if (!['awaiting_packaging', 'awaiting_deliver'].includes(row.status))"));
assert(orders.includes('statusText(row.status)'));
assert(orders.includes('orderEmptyText'), 'orders must expose a contextual empty state');
assert(orders.includes('正在读取订单'), 'orders must explain initial loading state');
assert(orders.includes('storeScopeOptions'), 'orders must expose a selectable store scope');
assert(orders.includes('全部店铺'), 'orders must support an all-store order scope');
assert(orders.includes('selectedStoreIds'), 'orders must resolve current, single-store, and all-store scopes');
assert(orders.includes('multiple') && orders.includes('collapse-tags'), 'orders store filter must support multi-select store selection');
assert(orders.includes('const storeScope = Vue.ref([CURRENT_STORE])'), 'orders store filter state must be an array for multi-select');
assert(orders.includes('normalized = [ALL_STORES]'), 'orders all-store option must be exclusive from concrete store selections');
assert(orders.includes('normalized = incoming.filter((item) => item !== ALL_STORES)'), 'orders concrete store selections must clear all-store mode');
assert(orders.includes('storeIds.length > 1'), 'orders multi-store selection must use aggregate fetching semantics');
assert(orders.includes('summaryRows'), 'order KPI cards must use an independent summary data source');
assert(orders.includes('fetchOrderSummary'), 'order KPI cards must fetch scope-level order summary');
assert(orders.includes('ORDER_SUMMARY_PAGE_SIZE'), 'order summary must page through Ozon orders instead of using the current table page only');
assert(orders.includes('kpiRows'), 'order KPI cards must use a dedicated weekly KPI data source');
assert(orders.includes('previousKpiRows'), 'order KPI cards must compare this week against the previous 7 days');
assert(orders.includes('weekKpiRanges'), 'order KPI cards must use this-week ranges');
assert(orders.includes('fetchOrderKpis'), 'order KPI cards must fetch weekly KPI data');
assert(orders.includes('isKpiGmvOrder'), 'order KPI GMV must filter to MY ERP effective order statuses');
assert(orders.includes("String(row.status || '').toLowerCase() !== 'cancelled'"), 'order KPI GMV must match MY ERP and exclude cancelled orders only');
assert(orders.includes('fetchOrdersForStores(storeIds, null)'), 'order KPI cards must use cached posting trend data instead of live Ozon windows');
assert(server.includes('display_status'), 'orders cache must preserve MY ERP style display status independently from live Ozon status');
assert(orders.includes('kpiOrderProfit'), 'order KPI profit must match MY ERP behavior when cost is missing');
assert(orders.includes('orderTotalCost'), 'order profit must use sales minus all known costs');
assert(orders.includes('orderOzonCost'), 'order profit must include Ozon/platform deductions');
assert(orders.includes('orderOutboundCost'), 'order profit must include order-level outbound cost');
assert(orders.includes('orderDelivered'), 'order profit must only calculate after delivery');
assert(orders.includes('已送达后计算'), 'non-delivered orders must not show misleading profit');
assert(orders.includes('本周 GMV'), 'order KPI copy must use MY ERP weekly GMV wording');
assert(orders.includes('本周利润'), 'order KPI copy must use MY ERP weekly profit wording');
assert(orders.includes('本周利润率'), 'order KPI copy must use MY ERP weekly profit-rate wording');
assert(orders.includes('vs 上 7 天'), 'order KPI copy must compare against the previous 7 days');
assert(!orders.includes('当前页 GMV'), 'order KPI copy must not describe current-page statistics');
assert(!orders.includes('范围 GMV'), 'order KPI copy must not use date-filter scope wording');
assert(orders.includes('label="订单金额"'), 'orders table must expose order amount as a dedicated column');
assert(orders.includes('label="利润"'), 'orders table must expose profit as a dedicated column');
assert(orders.includes('hasOrderProfit'), 'orders table must show a dash when profit cannot be calculated');
assert(!orders.includes('订单 {{ moneyText(row.total_cny) }}'), 'orders table must not bury amount inside the product cell');
assert(orders.includes('<el-dropdown trigger="click" placement="bottom-end" @command="handleRowAction">'), 'order row actions must use a MY ERP style overflow menu');
assert(orders.includes('<MoreFilled />'), 'order row actions must use a compact three-dot trigger');
assert(orders.includes('查看详情'), 'order row action menu must include detail action');
assert(orders.includes('编辑货源/采购'), 'order row action menu must include procurement action');
assert(orders.includes('saveProcurementSource'), 'order row procurement action must save source and purchase cost');
assert(orders.includes('保存并重算利润'), 'order procurement dialog must make profit recalculation explicit');
assert(server.includes('app.post("/api/seller/orders/:postingNumber/source"'), 'orders API must expose a procurement source update endpoint');
assert(server.includes('CREATE TABLE IF NOT EXISTS app_order_costs'), 'orders must store order-level outbound costs');
assert(server.includes('payload.outbound_cost_cny'), 'order procurement updates must rewrite cached order-level outbound cost');
assert(server.includes('payload.profit_cny'), 'order procurement updates must rewrite cached order profit');
assert(server.includes('Math.abs(financialToCny(fd.commission_amount'), 'order procurement save must convert negative Ozon commission into positive CNY cost');
assert(server.includes('financialCurrency = String(fd.currency_code || product.financial_currency_code || "RUB").toUpperCase()'), 'order procurement save must use Ozon financial currency for fee conversion');
assert(orders.includes('const orderCommission = (row) => roundMoney(Math.abs(Number(row.commission_cny || 0)))'), 'order UI must never show platform commission as a negative cost');
assert(orders.includes('找货源'), 'order row action menu must include sourcing action');
assert(orders.includes('立即备货'), 'order row action menu must include preparation action');
assert(orders.includes('cancelOrder'), 'order row action menu must wire cancel to the protected cancel flow');
assert(orders.includes("axios.post('/api/seller/orders/cancel'"), 'order cancel action must call the local protected cancel endpoint');
assert(orders.includes('cancel_reason_id'), 'order cancel UX must collect the Ozon cancel_reason_id');
assert(orders.includes('测试环境未启用沙箱开关时，后端会阻止真实调用'), 'order cancel UX must explain sandbox protection');
assert(server.includes('app.post("/api/seller/orders/cancel"'), 'orders API must expose a protected cancel endpoint');
assert(server.includes('OZON_ORDER_CANCEL_MODE === "sandbox"'), 'cancel endpoint must only execute real cancellation in sandbox mode by default');
assert(server.includes('OZON_ORDER_CANCEL_BASE_URL &&'), 'sandbox cancel mode must require an explicit sandbox base URL');
assert(server.includes('OZON_ORDER_CANCEL_BASE_URL !== OZON_SELLER_BASE_URL'), 'sandbox cancel mode must not fall back to the production Ozon base URL');
assert(server.includes('OZON_ORDER_CANCEL_ALLOW_PRODUCTION'), 'cancel endpoint must require an explicit production override for production cancellation');
assert(server.includes('callOzonSellerAPI("/v2/posting/fbs/cancel"'), 'cancel endpoint must integrate the real Ozon cancel API');
assert(server.includes('cancel_reason_id: cancelReasonId'), 'cancel endpoint must send Ozon cancel_reason_id');
assert(!server.includes('/v3/posting/fbs/cancel'), 'test cancel flow must not call the Ozon cancel API');
assert(orders.includes('width="72" fixed="right" align="center"'), 'order action column must stay compact enough to avoid clipping');
assert(orders.includes('grid-template-columns:240px 130px minmax(240px,1fr) 250px 70px 70px'), 'order filters must keep multi-store selection usable and the date range compact on desktop');
assert(orders.includes('dateRangeBounds'), 'order date filtering must share one explicit date-bound conversion');
assert(orders.includes('T00:00:00+08:00'), 'order date filter must start the selected day at China time');
assert(orders.includes('T23:59:59+08:00'), 'order date filter must end the selected day at China time');
assert(!orders.includes('new Date(sinceD).toISOString()'), 'order date filter must not parse YYYY-MM-DD as a browser-dependent instant');
assert(orders.includes("sync_mode: syncMode"), 'order list must send an explicit sync mode to separate cache refresh from Ozon sync');
assert(orders.includes("refreshOrderDashboard('cache')"), 'top refresh must reread local order cache only');
assert(orders.includes("refreshOrderDashboard('latest')"), 'auto/latest refresh must pull the latest Ozon orders intentionally');
assert(orders.includes("refreshOrderDashboard('in_progress')"), 'in-progress refresh must use a dedicated sync mode');
assert(orders.includes('openSyncWindowDialog'), 'set-time button must expose a sync-window setting');
assert(server.includes('syncMode !== "live"'), 'explicit order date filters should use cached MY ERP style data by default');
assert(server.includes('syncMode === "latest"'), 'orders API must support latest-order sync mode');
assert(server.includes('syncMode === "in_progress"'), 'orders API must support in-progress sync mode');
assert(orders.includes('effectiveStoreIdForOrder'), 'order row actions must use the row store id in all-store mode');
assert(orders.includes('store_id: effectiveStoreIdForOrder(row)'), 'order detail and batch actions must send the row store id');
assert(orders.includes('row.store_name || currentStoreName'), 'orders must show each row store name when listing all stores');
assert(orders.includes('确认发货至 Ozon'), 'orders must avoid exposing raw API endpoint text in the ship button');
assert(main.includes(`<shop-switcher v-if="routeName !== 'orders'"`), 'orders page must hide the global store switcher and use the local filter only');

assert(listing.includes("store_id: getStoreId() || undefined"));
assert(listing.includes("axios.get('/api/seller/listing-history', { params })"));
assert(listing.includes('syncTask'));
assert(listing.includes('pagination.currentPage'));
assert(listing.includes('retryTask'));
assert(listing.includes('exportHistory'));
assert(listing.includes('message_zh'));
assert(listing.includes('firstErrorText'), 'listing history must prefer backend first-error summaries in the visible table');
assert(listing.includes('error_summary'), 'listing history must consume backend error_summary when present');
assert(listing.includes('错误摘要'), 'listing detail must show a readable error summary before raw errors');
assert(server.includes('req.body?.taskId || req.body?.task_id'));
assert(server.includes('translateOzonListingError'));
assert(server.includes('/api/seller/listing-history/:id/retry'));
assert(server.includes('/api/seller/listing-history/export'));
assert(server.includes('function listingErrorSummary'), 'listing history must expose first-error and summary fields');
assert(server.includes('error_summary: readable.slice(0, 3).join("；")'), 'listing history must include human-readable error_summary');
assert(server.includes('first_error_message_zh'), 'listing history must include translated first error');
assert(server.includes("lh.task_id ILIKE"));
assert(server.includes("interval '1 day'"));
assert(main.includes('<span>单品找货</span>'), 'single sourcing v2 must be restored as an independent sidebar entry');
assert(main.includes("routeName === 'single-sourcing'"), 'single sourcing v2 route must render the real workflow');
assert(!main.includes("routeName === 'single-sourcing-frozen'"), 'single sourcing v2 must not render the old frozen notice');
for (const alias of ["#/selection", "#/history", "#/ai-image", "#/screen", "#/ranking"]) {
  assert(main.includes(`path === '${alias}'`), `route alias ${alias} must resolve to the intended module`);
}
assert(sourcing.includes('单品找货工作台'), 'single sourcing should read as a standalone operator workbench');
assert(sourcing.includes('currentWorker'), 'single sourcing must focus on the current online worker instead of historical offline noise');
assert(sourcing.includes('未检测到当前在线插件'), 'single sourcing must explain missing plugin state');
assert(sourcing.includes('插件需要重新授权'), 'single sourcing must explain unauthorised plugin state');
assert(sourcing.includes('1688 需要人工验证'), 'single sourcing must surface captcha/verification state');
assert(sourcing.includes('1688 登录状态不可用'), 'single sourcing must surface 1688 login state');
assert(sourcing.includes('AI 审核失败'), 'single sourcing must surface AI provider failures');
assert(sourcing.includes('Math.max(1, Number(maxCandidates.value || 5))'), 'candidate display must respect the user candidate count with default 5');
assert(sourcing.includes('最多展示 {{ maxCandidates }} 个候选/商品'), 'candidate count must be visible to the operator');
assert(sourcing.includes('MOQ {{ candidateMoq(c)'), 'candidate rows must expose MOQ');
assert(sourcing.includes('运费 {{ candidateFreight(c)'), 'candidate rows must expose freight status');
assert(sourcing.includes('重量 {{ candidateWeight(c)'), 'candidate rows must expose weight status');
assert(sourcing.includes('任务完成、失败或中断后都会保留在这里下载 Excel'), 'history empty state must explain export persistence');
assert(listing.includes("'ozon_processing'"), 'listing history must understand ozon_processing status');
assert(listing.includes('同步状态'), 'listing history must provide a clear sync action');
assert(listing.includes('部分商品需处理后重试'), 'listing history must explain partial success');
assert(listing.includes('label="partial_success"'), 'listing history must expose a partial-success filter');
assert(listing.includes('上架记录列表'), 'listing history should use user-facing listing history copy');
assert(listing.includes('暂无匹配的上架记录。可调整筛选条件；新记录会在批量上架提交后出现。'), 'listing history must have a non-misleading empty state');
assert(inventory.includes('暂无库存数据。请先选择店铺并点击同步 Ozon 全量；如已同步，可调整搜索条件。'), 'inventory must explain empty data and next step');
assert(batchUpload.includes('这不是创建完成'), 'batch upload completion copy must distinguish submitted from completed');
assert(batchUpload.includes('REQUIRED_BACKGROUND_VERSION = "2.2.9.100"'), 'batch upload must require the current released collector plugin');
assert(batchUpload.includes('pluginVersionOk'), 'batch upload must not show stale plugins as a healthy connection');
assert(batchUpload.includes('ensureRowsCollected'), 'batch upload must submit first, collect in the background, then continue listing');
assert(batchUpload.includes('createBatchListingPlaceholders'), 'batch upload must create visible listing-history placeholders before long plugin collection');
assert(batchUpload.includes('row_key: row._listingRowKey'), 'batch upload placeholders must track rows instead of deduplicating repeated SKUs');
assert(batchUpload.includes('/api/seller/listing-history/batch-start'), 'batch upload must persist batch placeholders before collection');
assert(batchUpload.includes('listingPlaceholderTaskId'), 'batch upload must bind the real Ozon task back to the visible placeholder');
assert(batchUpload.includes('一键解析+采集+上架'), 'batch upload primary action must describe async background processing');
assert(!batchUpload.includes('!items.filter(r=>r.valid&&r.distilled).length || !!items.filter'), 'batch upload primary action must not require pre-collected rows before submission');
assert(stores.includes('PLUGIN_MANIFEST_VERSION'), 'store management must expose manifest version');
assert(stores.includes('PLUGIN_ZIP_VERSION'), 'store management must expose zip version');
assert(stores.includes('class="store-management-container" style="background:#f8fafc'), 'store management must use the unified ERP workbench shell');
assert(stores.includes('element-loading-text="正在读取店铺"'), 'store management table must use the unified loading state');
assert(stores.includes('需要刷新插件'), 'store management must show plugin refresh guidance');
assert(stores.includes('小白检查顺序'), 'store management must show non-technical plugin install checks');
assert(stores.includes('批量上架开启水印增强时会使用此文字'), 'store management must explain how watermark text is used');
assert(stores.includes('refreshPluginStatus'), 'store management must allow refreshing plugin status');
assert(stores.includes('displayClientId'), 'store management must use a client id display helper');
assert(stores.includes('不会删除 Ozon 后台店铺'), 'store deletion must explain it only removes ERP authorization');
assert(stores.includes('暂无店铺授权。新增授权后才能同步商品、库存、订单和采集任务。'), 'store management must explain empty state');
assert(stores.includes('row.client_id_masked'), 'store management must prefer backend masked client id');
assert(stores.includes('row.client_id_last4'), 'store management must support backend client id last4 fallback');
assert(stores.includes('maskClientId(row.client_id)'), 'store management must keep legacy local masking fallback');
assert(shopSwitcher.includes('displayClientId'), 'shop switcher must use a client id display helper');
assert(shopSwitcher.includes('shop.client_id_masked'), 'shop switcher must prefer backend masked client id');
assert(shopSwitcher.includes('shop.client_id_last4'), 'shop switcher must support backend client id last4 fallback');
assert(shopSwitcher.includes('maskClientId(shop.client_id)'), 'shop switcher must keep legacy local masking fallback');

console.log('Inventory, orders, and listing history structural checks passed.');
