const fs = require('fs');
const assert = require('assert');
const server = fs.readFileSync('server.js', 'utf8');
const view = fs.readFileSync('public/js/views/MarketDiscovery.js', 'utf8');
const main = fs.readFileSync('public/js/main.js', 'utf8');
const index = fs.readFileSync('public/index.html', 'utf8');

for (const table of ['app_top_lists', 'app_china_sellers', 'app_auto_listing_items', 'app_auto_listing_settings', 'app_auto_listing_events']) assert(server.includes(`CREATE TABLE IF NOT EXISTS ${table}`));
for (const route of ['/api/sourcing/bestsellers', '/api/sourcing/discover-products', '/api/sourcing/opportunity-collector/status', '/api/sourcing/opportunity-collector/run', '/api/sourcing/bestsellers/import', '/api/sourcing/china-zone', '/api/sourcing/china-zone/verify']) assert(server.includes(route));
for (const route of ['/api/auto-listing/dashboard', '/api/auto-listing/discover', '/api/auto-listing/items', '/api/auto-listing/settings']) assert(server.includes(route));
assert.match(server, /app\.get\(\"\/api\/auto-listing\/items\/:id\/events\"/);
assert.match(server, /app\.post\(\"\/api\/auto-listing\/items\/start-sourcing\"/);
assert.match(server, /syncAutoListingItemFromSourcingResult/);
assert.match(server, /sourcing_result/);
assert.match(server, /app\.patch\(\"\/api\/auto-listing\/items\/:id\"/);
assert.match(server, /app\.delete\(\"\/api\/auto-listing\/items\/:id\"/);
assert.match(server, /action === "delete"/);
assert.match(server, /payload\.blue_ocean_score/);
assert(view.includes("split(',').map(value => value.trim()).find(Boolean)"));
assert(server.includes('discoverOzonProductsFromPlatformCategories'));
assert(server.includes('OZON_OPPORTUNITY_REFRESH_INTERVAL_MS'));
assert(server.includes('maybeRefreshOzonOpportunityPool'));
assert(server.includes('GEO_BLUE_OCEAN_OUTPUT_ROOT'));
assert(server.includes('importGeoBlueOceanScored'));
assert(server.includes('geo_ozon_blue_ocean'));
assert(server.includes('Ozon 机会池只采集平台商品候选；不会自动请求 1688'));
assert(!server.includes("source_policy: 'myerp_ozon_platform_category_fallback'"), 'market discovery must not fall back to MYERP category rows');
assert(server.includes('PRODUCT_LEVEL_SOURCE_UNAVAILABLE'));
assert(server.includes('Ozon 公共搜索没有返回商品链接'));
assert(server.includes('categorySearchTerms'));
assert(server.includes('товары для дома'));
assert(server.includes('ozon_public_category_discovery'));
assert(server.includes('app_platform_categories c'));
assert(server.includes('WHERE user_id = $1 AND store_id = $2 AND description_category_id = $3'));
assert.match(server, /source_name\/source_captured_at/);
assert.match(server, /req\.user\.role !== 'admin'/);
assert.match(server, /confidence: 0\.65/);
assert.match(server, /isChina: false, confidence: 0\.65/);
assert(!view.includes('Ozon 机会池不会自动跑 1688'), 'market discovery must not show the persistent "机会池不会自动跑1688" alert');
assert.match(view, /runOpportunityCollector/);
assert.match(view, /collectorStatus/);
assert.match(view, /collectorResult/);
assert.match(view, /collectorResultText/);
assert.match(view, /加入找货候选/);
assert.match(view, /view: marketView\.value/);
assert.match(view, /wait: true/);
assert.match(view, /本次没有采集到 Ozon 商品候选/);
assert(!view.includes('点击采集会同步返回导入数和失败原因'), 'market discovery must not show the removed persistent collector hint');
assert(!view.includes('/api/sourcing/category-opportunities'), 'market discovery must not prefer own-store category analytics as platform data');
assert.match(view, /选品 → 找货 → 上架 主流程|商品流水线/);
assert.match(view, /规则中心/);
assert.match(view, /选品规则/);
assert.match(view, /market-filter-bar/);
assert.match(view, /商品机会/);
assert.match(view, /rowImage/);
assert.match(view, /rowRevenue/);
assert.match(view, /rulesOnly/);
assert.match(view, /规则通过入池/);
assert.match(view, /openQueueDetail/);
assert.match(view, /startSourcingJob/);
assert.match(view, /启动真实找货/);
assert.match(view, /single-sourcing-review/);
assert.match(view, /saveQueueNote/);
assert.match(view, /removeQueueRow/);
assert.match(view, /detailDrawer/);
assert.match(view, /el-drawer/);
assert.match(index, /market-status-strip/);
assert.match(index, /market-flow-strip/);
assert.match(view, /marketSummary/);
assert.match(view, /source_payload/);
assert.match(view, /min_blue_ocean_score/);
assert.match(view, /signalText\(row,'demand'\)/);
assert.match(view, /profit_score/);
assert.match(view, /risk_score/);
assert.match(server, /source_payload, updated_at/);
assert.match(server, /product_name/);
assert.match(server, /sales_30d/);
assert.match(server, /image_url/);
assert.match(server, /scraped_at/);
assert.match(server, /blue_ocean_score: row\.source_payload/);
assert.match(view, /discoverSelected/);
assert.match(view, /discoverProductsFromCategories/);
assert.match(view, /discoveryState/);
assert.match(view, /discoveryErrorText/);
assert.match(view, /暂时没有商品级榜单数据/);
assert.match(view, /discoverCategoryLabel/);
assert.match(view, /primaryDiscoverLabel/);
assert.match(view, /采集 Ozon 机会池/);
assert(!view.includes('从类目发现商品 ({{selectedCategoryCount || 3}})'), 'category discovery button must not show fallback category count as discovered products');
assert.match(view, /请先勾选商品机会/);
assert.match(view, /marketRowSelectable/);
assert.match(view, /submit_to_ozon/);
assert.match(server, /\/api\/sourcing\/category-analysis/);
assert.match(view, /browseCategory/);
assert.match(view, /类目机会总览/);
console.log('Market discovery structural checks passed.');
