const fs = require('fs');
const assert = require('assert');
const server = fs.readFileSync('server.js', 'utf8');
const view = fs.readFileSync('public/js/views/MarketDiscovery.js', 'utf8');
const main = fs.readFileSync('public/js/main.js', 'utf8');

for (const table of ['app_top_lists', 'app_china_sellers', 'app_auto_listing_items', 'app_auto_listing_settings', 'app_auto_listing_events']) assert(server.includes(`CREATE TABLE IF NOT EXISTS ${table}`));
for (const route of ['/api/sourcing/bestsellers', '/api/sourcing/discover-products', '/api/sourcing/bestsellers/import', '/api/sourcing/china-zone', '/api/sourcing/china-zone/verify']) assert(server.includes(route));
for (const route of ['/api/auto-listing/dashboard', '/api/auto-listing/discover', '/api/auto-listing/items', '/api/auto-listing/settings']) assert(server.includes(route));
assert(view.includes("split(',').map(value => value.trim()).find(Boolean)"));
assert(server.includes('myerp_ozon_platform_category_fallback'));
assert(server.includes('discoverOzonProductsFromPlatformCategories'));
assert(server.includes('PRODUCT_LEVEL_SOURCE_UNAVAILABLE'));
assert(server.includes('Ozon 公共搜索没有返回商品链接'));
assert(server.includes('categorySearchTerms'));
assert(server.includes('товары для дома'));
assert(server.includes('ozon_public_category_discovery'));
assert(server.includes('app_platform_categories c'));
assert(server.includes('WHERE user_id = $1 AND store_id = $2 AND description_category_id = $3'));
assert.match(server, /source_name\/source_captured_at/);
assert.match(server, /req\.user\.role !== 'admin'/);
assert.match(server, /confidence: 0\.65/);
assert.match(server, /isChina: false, confidence: 0\.65/);
assert.match(view, /自动上架/);
assert.match(view, /商品流水线/);
assert.match(view, /规则中心/);
assert.match(view, /discoverSelected/);
assert.match(view, /discoverProductsFromCategories/);
assert.match(view, /discoveryState/);
assert.match(view, /discoveryErrorText/);
assert.match(view, /暂时没有商品级榜单数据/);
assert.match(view, /discoverCategoryLabel/);
assert.match(view, /primaryDiscoverLabel/);
assert.match(view, /从当前类目发现商品/);
assert(!view.includes('从类目发现商品 ({{selectedCategoryCount || 3}})'), 'category discovery button must not show fallback category count as discovered products');
assert.match(view, /类目级平台数据/);
assert.match(view, /marketRowSelectable/);
assert.match(view, /submit_to_ozon/);
assert.match(main, /market-discovery-view/);
console.log('Market discovery structural checks passed.');
